name: string_capitalize
description: Simple extension for Dart language to capitalize our strings
version: 0.0.2
homepage: https://github.com/LeonardoRosaa/string_capitalize

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
