name: string_capitalize
description: Simple extension for Dart language to capitalize our strings
version: 0.0.4
homepage: https://github.com/LeonardoRosaa/string_capitalize

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
